### ISSUE TITLE
broken links to episodes

### ISSUE THREAD

**Issue by k8hertweck** [carpentries-incubator/SDC-BIDS-EEG-EEGLAB#2]
I received the following email (I'm listed as a contact in the issue template, a holdover from the original Carpentries lesson templates). Passing along the info to you all!

----

Hi,

I got the chance to get to know this repository via BIDS-Matlab meeting by James Desjardins. However, the links for Episodes (https://github.com/carpentries-incubator/SDC-BIDS-EEG-EEGLAB) seem not to work for me. Therefore I report this issue to you wish the links are available so that I can share this nice source with people who want to get to know more EEGLAB and BIDS. Thank you so much for your help in this matter!

Best regards,
Yu-Fang  

-- 

Yu-Fang Yang
Postdoctoral fellow
Psychological Sciences Research Institute (IPSY)
University of Louvain
Place Cardinal Mercier 10, 1348 Louvain-la-Neuve, Belgium
https://yufang-yang.com/

**Comment by SaraStephenson** [comment]
Episode links have been updated. Thank you for passing on the message!
